### PR TITLE
chore: fix duplicate API requests

### PR DESCRIPTION
**Pull request by adamgrharvey**

### CODE REVIEW

**Comment by weslord** [comment]
The code looks fine, but I want to confirm we really need to do this. I'll return to this this afternoon to get a better understanding of the connection/credential/proof/etc lifecycle.

During my investigations I found a handful of pre-existing issues related to how connections are managed in the redux store. Will send separately as they aren't strictly related to this PR.

**Comment by jleach** [comment]
@weslord Ok to merge or do you need some more time?

**Review by weslord — APPROVED** [review]
@adamgrharvey Please include a link to the source of `useEffectOnce` in a comment at the top of the file. Otherwise ready to merge.

**Comment by weslord** [comment]
@jleach I would recommend revisiting this (and #33) at some point in the future.

In the cases where a double request causes race conditions and lifecycle problems (eg: multiple requests in the wallet app, mismatched connections), those underlying problems should be fixed. In the other cases where double requests cause no side-effects but are simply redundant, there is no need to mitigate.

For now, this solves some actual problems and appears to do more good than harm. Fine by me to merge in.

**Review by jleach — APPROVED** [review]

**Pull request merged**
