### PR TITLE
chore: remove `explicit-any` global ignore, review each instance of `any`

### PR DESCRIPTION
**Pull request by adamgrharvey**

### CODE REVIEW

**Comment by adamgrharvey** [comment]
@weslord

**Comment by weslord** [comment]
Given this some thought and would recommend leaving the global rule instead of inline overrides.

- Inline overrides imply a deliberate long-term choice to use `any`.
- Much easier to disable the global rule to find all these when improving types in the future.

I would also recommend running `yarn test:lint` after changing the top-level `.eslintrc.js`, looks like there are a bunch of explicit-any warnings on the backend now.

**Review by jleach — APPROVED** [review]

**Comment by jleach** [comment]
@adamgrharvey Sorry, missed @weslord commend and merged this.

**Comment by adamgrharvey** [comment]
> @adamgrharvey Sorry, missed @weslord commend and merged this.

No problem, I will eventually go through and refactor the instances of `any` and resolve it anyway.

**Pull request merged**
